### PR TITLE
Add Selection_Sort Implementation

### PR DESCRIPTION
**Pull request by sannanansari**
78f9704 is Correct.
Sorry for 15 commits. This is my first contribution.

### CODE REVIEW

**Comment by sannanansari** [comment]
Corrected

**Comment by MadhavBahlMD** [comment]
LGTM 

I will review the code by evening, and merge it after that . 

Keep up the good work :)

**Comment by sannanansari** [comment]
Thanks

**Comment by sannanansari** [comment]
Thanks for your help.I have learn many thing on this project.



Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: MADHAV BAHL <notifications@github.com> Date: 10/07/2018  9:17 p.m.  (GMT+05:30) To: MadhavBahlMD/OOPS <OOPS@noreply.github.com> Cc: Sanan <asannan822@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [MadhavBahlMD/OOPS] Add Selection_Sort Implementation (#17) 
Merged #17.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MadhavBahlMD/OOPS","title":"MadhavBahlMD/OOPS","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MadhavBahlMD/OOPS"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Merged #17."}],"action":{"name":"View Pull Request","url":"https://github.com/MadhavBahlMD/OOPS/pull/17#event-1725892605"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MadhavBahlMD/OOPS/pull/17#event-1725892605",
"url": "https://github.com/MadhavBahlMD/OOPS/pull/17#event-1725892605",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [MadhavBahlMD/OOPS] Add Selection_Sort Implementation (#17)",
"sections": [
{
"text": "",
"activityTitle": "**MADHAV BAHL**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@MadhavBahlMD",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/MadhavBahlMD/OOPS/pull/17#event-1725892605"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 354438187\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by MadhavBahlMD** [comment]
Hey @sannanansari I just checked the file once, please make the following changes and submit the PR again:

1. Please check the spellings
image

2. Please follow proper Markdown Lint/format
image

3. Please add a link at the end of the readme which will open the code

Something like this: 
```
# [See the Code Here](Path to file)
```

**Comment by sannanansari** [comment]
I have Corrected it.

**Pull request merged**
